-- MySQL Script generated by MySQL Workbench
-- Fri May 19 09:36:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema database_project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `database_project` ;

-- -----------------------------------------------------
-- Schema database_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_project` DEFAULT CHARACTER SET utf8 ;
USE `database_project` ;

-- -----------------------------------------------------
-- Table `database_project`.`ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`ciudad` ;

CREATE TABLE IF NOT EXISTS `database_project`.`ciudad` (
  `idCiudad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCiudad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`cliente` ;

CREATE TABLE IF NOT EXISTS `database_project`.`cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `telefono` MEDIUMTEXT NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `Ciudad` INT(11) NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Ciudad1_idx` (`Ciudad` ASC),
  CONSTRAINT `fk_Cliente_Ciudad1`
    FOREIGN KEY (`Ciudad`)
    REFERENCES `database_project`.`ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`formapago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`formapago` ;

CREATE TABLE IF NOT EXISTS `database_project`.`formapago` (
  `idFormaPago` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFormaPago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`tipousuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`tipousuario` ;

CREATE TABLE IF NOT EXISTS `database_project`.`tipousuario` (
  `idTipoUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`usuario` ;

CREATE TABLE IF NOT EXISTS `database_project`.`usuario` (
  `cc` INT(11) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `edad` INT(11) NOT NULL,
  `userName` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `TipoUsuario` INT(11) NOT NULL,
  `Ciudad` INT(11) NOT NULL,
  PRIMARY KEY (`cc`),
  INDEX `fk_Usuario_TipoUsuario1_idx` (`TipoUsuario` ASC),
  INDEX `fk_Usuario_Ciudad1_idx` (`Ciudad` ASC),
  CONSTRAINT `fk_Usuario_Ciudad1`
    FOREIGN KEY (`Ciudad`)
    REFERENCES `database_project`.`ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_TipoUsuario1`
    FOREIGN KEY (`TipoUsuario`)
    REFERENCES `database_project`.`tipousuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`factura` ;

CREATE TABLE IF NOT EXISTS `database_project`.`factura` (
  `idFactura` INT(11) NOT NULL AUTO_INCREMENT,
  `Cliente` INT(11) NOT NULL,
  `Usuario_cc` INT(11) NOT NULL,
  `FormaPago` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Cliente1_idx` (`Cliente` ASC),
  INDEX `fk_Factura_Usuario1_idx` (`Usuario_cc` ASC),
  INDEX `fk_Factura_FormaPago1_idx` (`FormaPago` ASC),
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`Cliente`)
    REFERENCES `database_project`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_FormaPago1`
    FOREIGN KEY (`FormaPago`)
    REFERENCES `database_project`.`formapago` (`idFormaPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Usuario1`
    FOREIGN KEY (`Usuario_cc`)
    REFERENCES `database_project`.`usuario` (`cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`producto` ;

CREATE TABLE IF NOT EXISTS `database_project`.`producto` (
  `idProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `Usuario_cc` INT(11) NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Usuario1_idx` (`Usuario_cc` ASC),
  CONSTRAINT `fk_Producto_Usuario1`
    FOREIGN KEY (`Usuario_cc`)
    REFERENCES `database_project`.`usuario` (`cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`detallefac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`detallefac` ;

CREATE TABLE IF NOT EXISTS `database_project`.`detallefac` (
  `Factura` INT(11) NOT NULL,
  `Producto` INT(11) NOT NULL,
  `cantidad` DOUBLE NOT NULL,
  `valor` INT(11) NOT NULL,
  PRIMARY KEY (`Factura`, `Producto`),
  INDEX `fk_Factura_has_Producto_Producto1_idx` (`Producto` ASC),
  INDEX `fk_Factura_has_Producto_Factura1_idx` (`Factura` ASC),
  CONSTRAINT `fk_Factura_has_Producto_Factura1`
    FOREIGN KEY (`Factura`)
    REFERENCES `database_project`.`factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_has_Producto_Producto1`
    FOREIGN KEY (`Producto`)
    REFERENCES `database_project`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`tipoproducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`tipoproducto` ;

CREATE TABLE IF NOT EXISTS `database_project`.`tipoproducto` (
  `idTipoProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`idTipoProducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`proovedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`proovedor` ;

CREATE TABLE IF NOT EXISTS `database_project`.`proovedor` (
  `idProovedor` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(35) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `telefono` DOUBLE NOT NULL,
  `Ciudad` INT(11) NOT NULL,
  `TipoProducto` INT(11) NOT NULL,
  PRIMARY KEY (`idProovedor`),
  INDEX `fk_Proovedor_Ciudad1_idx` (`Ciudad` ASC),
  INDEX `fk_Proovedor_TipoProducto1_idx` (`TipoProducto` ASC),
  CONSTRAINT `fk_Proovedor_Ciudad1`
    FOREIGN KEY (`Ciudad`)
    REFERENCES `database_project`.`ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proovedor_TipoProducto1`
    FOREIGN KEY (`TipoProducto`)
    REFERENCES `database_project`.`tipoproducto` (`idTipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`facturacompra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`facturacompra` ;

CREATE TABLE IF NOT EXISTS `database_project`.`facturacompra` (
  `idFacturaCompra` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `Usuario_cc` INT(11) NOT NULL,
  `Proovedor` INT(11) NOT NULL,
  PRIMARY KEY (`idFacturaCompra`),
  INDEX `fk_FacturaCompra_Usuario1_idx` (`Usuario_cc` ASC),
  INDEX `fk_FacturaCompra_Proovedor1_idx` (`Proovedor` ASC),
  CONSTRAINT `fk_FacturaCompra_Proovedor1`
    FOREIGN KEY (`Proovedor`)
    REFERENCES `database_project`.`proovedor` (`idProovedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FacturaCompra_Usuario1`
    FOREIGN KEY (`Usuario_cc`)
    REFERENCES `database_project`.`usuario` (`cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`detallefaccompra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`detallefaccompra` ;

CREATE TABLE IF NOT EXISTS `database_project`.`detallefaccompra` (
  `Producto` INT(11) NOT NULL,
  `FacturaCompra` INT(11) NOT NULL,
  `cantidad` DOUBLE NOT NULL,
  `valor` INT(11) NOT NULL,
  PRIMARY KEY (`Producto`, `FacturaCompra`),
  INDEX `fk_Producto_has_FacturaCompra_FacturaCompra1_idx` (`FacturaCompra` ASC),
  INDEX `fk_Producto_has_FacturaCompra_Producto1_idx` (`Producto` ASC),
  CONSTRAINT `fk_Producto_has_FacturaCompra_FacturaCompra1`
    FOREIGN KEY (`FacturaCompra`)
    REFERENCES `database_project`.`facturacompra` (`idFacturaCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_FacturaCompra_Producto1`
    FOREIGN KEY (`Producto`)
    REFERENCES `database_project`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`tiposervicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`tiposervicio` ;

CREATE TABLE IF NOT EXISTS `database_project`.`tiposervicio` (
  `idTipoServicio` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`idTipoServicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`servicio` ;

CREATE TABLE IF NOT EXISTS `database_project`.`servicio` (
  `idServicio` INT(11) NOT NULL AUTO_INCREMENT,
  `precio` DOUBLE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `TipoServicio` INT(11) NOT NULL,
  PRIMARY KEY (`idServicio`),
  INDEX `fk_Servicio_TipoServicio1_idx` (`TipoServicio` ASC),
  CONSTRAINT `fk_Servicio_TipoServicio1`
    FOREIGN KEY (`TipoServicio`)
    REFERENCES `database_project`.`tiposervicio` (`idTipoServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`facturaservicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`facturaservicio` ;

CREATE TABLE IF NOT EXISTS `database_project`.`facturaservicio` (
  `idFacturaServicio` INT(11) NOT NULL AUTO_INCREMENT,
  `Cliente` INT(11) NOT NULL,
  `Usuario_cc` INT(11) NOT NULL,
  `FormaPago` INT(11) NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`idFacturaServicio`),
  INDEX `fk_VentaServicio_Cliente1_idx` (`Cliente` ASC),
  INDEX `fk_FacturaServicio_Usuario1_idx` (`Usuario_cc` ASC),
  INDEX `fk_FacturaServicio_FormaPago1_idx` (`FormaPago` ASC),
  CONSTRAINT `fk_FacturaServicio_FormaPago1`
    FOREIGN KEY (`FormaPago`)
    REFERENCES `database_project`.`formapago` (`idFormaPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FacturaServicio_Usuario1`
    FOREIGN KEY (`Usuario_cc`)
    REFERENCES `database_project`.`usuario` (`cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VentaServicio_Cliente1`
    FOREIGN KEY (`Cliente`)
    REFERENCES `database_project`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`detalleventaservicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`detalleventaservicio` ;

CREATE TABLE IF NOT EXISTS `database_project`.`detalleventaservicio` (
  `FacturaServicio` INT(11) NOT NULL,
  `Servicio` INT(11) NOT NULL,
  `Horas` TIME NOT NULL,
  PRIMARY KEY (`FacturaServicio`, `Servicio`),
  INDEX `fk_VentaServicio_has_Servicio_Servicio1_idx` (`Servicio` ASC),
  INDEX `fk_VentaServicio_has_Servicio_VentaServicio1_idx` (`FacturaServicio` ASC),
  CONSTRAINT `fk_VentaServicio_has_Servicio_Servicio1`
    FOREIGN KEY (`Servicio`)
    REFERENCES `database_project`.`servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VentaServicio_has_Servicio_VentaServicio1`
    FOREIGN KEY (`FacturaServicio`)
    REFERENCES `database_project`.`facturaservicio` (`idFacturaServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`imagenproducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`imagenproducto` ;

CREATE TABLE IF NOT EXISTS `database_project`.`imagenproducto` (
  `idImagenProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(20) NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  `idProducto` INT(11) NOT NULL,
  PRIMARY KEY (`idImagenProducto`, `idProducto`),
  INDEX `fk_ImagenProducto_Producto1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_ImagenProducto_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `database_project`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `database_project`.`proyecto` (
  `idProyecto` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  `empresa` VARCHAR(40) NOT NULL,
  `Usuario_cc` INT(11) NOT NULL,
  PRIMARY KEY (`idProyecto`, `Usuario_cc`),
  INDEX `fk_Proyecto_Usuario1_idx` (`Usuario_cc` ASC),
  CONSTRAINT `fk_Proyecto_Usuario1`
    FOREIGN KEY (`Usuario_cc`)
    REFERENCES `database_project`.`usuario` (`cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `database_project`.`imagenproyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_project`.`imagenproyecto` ;

CREATE TABLE IF NOT EXISTS `database_project`.`imagenproyecto` (
  `idImagenProyecto` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(20) NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  `idProyecto` INT(11) NOT NULL,
  PRIMARY KEY (`idImagenProyecto`, `idProyecto`),
  INDEX `fk_ImagenProyecto_Proyecto1_idx` (`idProyecto` ASC),
  CONSTRAINT `fk_ImagenProyecto_Proyecto1`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `database_project`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
